## Session \# 1 Homework

#### Question 1

In [56]:
import numpy as np

print(np.__version__)

1.23.2


#### Question 2

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-05 11:51:43--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.1s    

2022-09-05 11:51:43 (11.9 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [64]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.shape[0])

11914


#### Question 3

In [50]:
print(df.Make.value_counts().head(3))

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64


#### Question 4

In [37]:
df[df.Make == 'Audi'].Model.nunique()

34

#### Question 5

In [43]:
df.isnull().any(axis=0).sum()

5

#### Question 6

In [65]:
df['Engine Cylinders'].median()

6.0

In [66]:
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [67]:
df['Engine Cylinders'].fillna(4.0, inplace=True)

In [68]:
df['Engine Cylinders'].median()

6.0

No. Although the number of 4.0's increased, the median is still 6.0

#### Question 7

In [81]:
X = np.array(df[df.Make == 'Lotus'][['Engine HP', 'Engine Cylinders']].drop_duplicates())
print(X)

[[189.   4.]
 [218.   4.]
 [217.   4.]
 [350.   8.]
 [400.   6.]
 [276.   6.]
 [345.   6.]
 [257.   4.]
 [240.   4.]]


In [83]:
XTX = np.dot(X.T, X)
print(XTX)

[[7.31684e+05 1.34100e+04]
 [1.34100e+04 2.52000e+02]]


In [85]:
inv_XTX = np.linalg.inv(XTX)
print(inv_XTX)

[[ 5.53084235e-05 -2.94319825e-03]
 [-2.94319825e-03  1.60588447e-01]]


In [89]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
print(y)

[1100  800  750  850 1300 1000 1000 1300  800]


In [91]:
w = np.dot(np.dot(inv_XTX, X.T), y)
print(w)

[  4.59494481 -63.56432501]


In [92]:
print(w[0])

4.594944810094551
